# Generated by Django 2.2.8 on 2019-12-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_homepagegalleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecarouselimages',
            name='caption',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.DeleteModel(
            name='HomePageGalleryImage',
        ),
    ]
